// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4FGnzVcx0HA0B_yq-FJWsL4b5zPlzS6c',
    appId: '1:846534950509:android:1d624ae09a02e8e9bd0964',
    messagingSenderId: '846534950509',
    projectId: 'strokemaster-ad8e6',
    storageBucket: 'strokemaster-ad8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_48utl1p5gn_ysLYeRFdIu3aHEaY-AjM',
    appId: '1:846534950509:ios:1d78caca6fe9493dbd0964',
    messagingSenderId: '846534950509',
    projectId: 'strokemaster-ad8e6',
    storageBucket: 'strokemaster-ad8e6.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

}