List<String> quotes = [
  "Master the stroke, and the speed will follow.",
  "The best paddlers don’t just race the water, they read it.",
  "Smoothness in your stroke is the key to power in your push.",
  "Consistency in technique is the foundation of speed.",
  "A perfect stroke is a conversation between body and boat.",
  "Technique is built one perfect stroke at a time.",
  "You can’t rush technique. Trust the process, and the results will come.",
  "The power of a strong paddler lies in the efficiency of their stroke.",
  "The fastest athlete isn’t always the strongest, but the one who perfects the technique.",
  "Speed comes from control, and control comes from perfect technique.",
  "A flawless stroke is the result of perfect timing, rhythm, and balance.",
  "Master the catch, and the release will follow.",
  "If your paddle doesn’t feel like an extension of your body, you’re not paddling yet.",
  "Each stroke is an opportunity to refine your skill and power.",
  "The more you focus on the details, the bigger the payoff in speed.",
  "In sprint canoeing, precision outpaces raw power every time.",
  "Focus on the finish—where the paddle meets the water makes all the difference.",
  "Effort is important, but technique makes the effort count.",
  "Your stroke is your signature. Make it powerful and precise.",
  "The art of paddling is in learning how to create the most power with the least effort.",
  "Warm up your body before the race, but don’t forget to warm up your mind.",
  "A proper warm-up sets the stage for a performance that surpasses the limit.",
  "Prepare your muscles, prime your mind, and get ready to race.",
  "The race doesn’t start at the starting line—it starts with the warm-up.",
  "A well-executed warm-up is a promise to your body that it’s time to perform.",
  "Prepare for the start like it’s the most important part of your race.",
  "Warm up thoroughly so that every stroke feels effortless from the start.",
  "The key to a strong race is a well-planned warm-up that gets you moving without fatigue.",
  "A proper warm-up means less energy wasted and more power delivered.",
  "Activate your core, engage your legs, and bring your arms to life before the race.",
  "Never skip the warm-up. It’s not just about getting ready—it’s about getting ahead.",
  "Flexibility and activation are your secret weapons in any sprint race.",
  "Take time to warm up. Your body will thank you when it’s time to compete.",
  "A great warm-up is a ritual—a set routine that gets you in the zone.",
  "The race is won before the start if your warm-up is spot-on.",
  "Start your warm-up with dynamic movements to bring your body to life.",
  "A good warm-up ensures you don’t just finish the race—you dominate it.",
  "Pre-race nerves are nothing a good warm-up can't manage.",
  "Think of your warm-up as a rehearsal for your race. Perfect it, and the performance will follow.",
  "Efficient warm-ups turn potential energy into kinetic power on the water.",
  "Activate your body in layers—work from the core to the extremities.",
  "Mental preparation is just as important as physical—so calm your mind during the warm-up.",
  "Your warm-up is the bridge between practice and peak performance.",
  "A great warm-up builds confidence by allowing you to feel strong and prepared.",
  "Warm up like the race depends on it—because it does.",
  "Don’t rush your warm-up—quality is better than quantity.",
  "With the right warm-up, you’re already racing before the gun goes off.",
  "The body that is properly warmed up is more than ready to race hard.",
  "The warm-up is the start of your race; treat it with the same focus and effort.",

  "Good technique begins with a strong set-up; the rest of the stroke flows from there.",
  "Your body is the engine, the paddle is your tool, and the kayak is your vehicle—master them all.",
  "A well-executed stroke relies on the right muscles working in the right sequence at the right time.",
  "Posture is the foundation of paddling efficiency; sit upright, engage your core, and let your power flow.",
  "The perfect catch starts with a clean paddle entry—aim to grip the water, not splash it.",
  "Force applied at a positive paddle angle translates into speed; avoid pulling at a negative angle.",
  "Propulsion is about creating force and transferring it efficiently through the paddle into the water.",
  "The paddle should exit the water before it passes your hip—anything beyond that wastes energy.",
  "Rotate from your hips and torso, not your shoulders, for maximum efficiency in every stroke.",
  "Balance is key; without it, even the best technique can fall apart.",
  "A strong catch begins with the blade fully submerged at a steep angle—lock in before applying force.",
  "The drive phase is led by your legs and hips, not your arms—let the big muscles do the work.",
  "The paddle works best when it stays vertical and close to the boat during the stroke.",
  "Every stroke should feel like an extension of your body—seamless and fluid.",
  "Avoid overextending the stroke; efficiency beats brute force every time.",
  "Power is maximized when the body moves as a unit—arms, torso, and legs working in harmony.",
  "The paddle blade must stay square to the water to maximize grip and prevent slippage.",
  "Incorporate a slight forward lean for optimal posture, but keep your spine straight and engaged.",
  "Avoid compressing side to side or forward and backward—stay stable and controlled.",
  "Maintain constant connection with the footrest to drive power through your legs into the stroke.",
  "Keep your top hand stable during the stroke; it locks the blade and ensures maximum efficiency.",
  "Efficiency is about minimizing wasted motion—every movement should contribute to propulsion.",
  "A quick and clean exit sets you up for a smooth transition into the next stroke.",
  "The paddle blade should travel gradually outward from the boat as the stroke progresses.",
  "Maximize your paddle’s grip on the water by keeping it aligned with the boat’s bow wake.",
  "A solid setup position minimizes injury risk and optimizes power delivery.",
  "Use your larger muscle groups—legs, glutes, and core—to generate most of the force.",
  "Avoid unnecessary movements that cause active drag; keep your kayak steady and smooth.",
  "A vertical paddle angle at the catch increases efficiency and reduces yaw.",
  "Effective paddling is about finding balance between stroke rate and distance per stroke.",
  "Focus on proper timing and sequencing; the right rhythm amplifies your power.",
  "Keep your shoulders relaxed, and let your core drive the movement.",
  "Optimal paddling is about working smarter, not harder.",
  "A stable top hand creates a higher pivot point, keeping your blade vertical longer.",
  "Precision in paddle placement is the hallmark of a great paddler.",
  "Shorter water time allows for quicker transitions and higher stroke rates.",
  "A well-timed leg drive starts just as the paddle catches the water.",
  "The boat moves fastest when your body weight shifts towards the pulling side.",
  "Control the exit with your knuckles leading, not your shoulder or elbow.",
  "Maximizing propulsion is about working within your muscles’ optimal range of motion.",
  "Maintain your paddle’s positive angle for as long as possible; it ensures forward momentum.",
  "Effective technique is as much about avoiding errors as it is about executing correctly.",
  "Minimize air time and maximize water time—every moment out of the water is a lost opportunity.",
  "A quick, efficient exit ensures you can set up the next stroke without losing momentum.",
  "Focus on small, consistent improvements; technique mastery is a journey, not a destination.",

  "Precision in the setup position is the foundation of every great stroke.",
  "Lead every movement with your hips and legs—they are the true drivers of power.",
  "Keep your paddle blade at a 45-50 degree angle for an optimal catch.",
  "A strong exit sets up the next stroke—lift your paddle out before it passes your hip.",
  "Connection is key; feel the link between your hands, legs, and footrest in every stroke.",
  "Stay upright, slightly forward of vertical, with a long spine for perfect posture.",
  "Set your scapulae—keep your shoulder blades back and down for maximum control.",
  "Your paddle blade should grip the water, not slip through it.",
  "Controlled, purposeful movements build efficiency; rush nothing.",
  "Focus on the timing between your catch and leg drive for seamless power transfer.",
  "Shift your weight towards the pulling side to enhance your stroke.",
  "Avoid excessive body movements—efficiency is about stability and control.",
  "Minimize air time; every moment in the water propels you forward.",
  "Train with your eyes closed to develop a feel for the stroke, not just the motion.",
  "The setup drill: your backhand at 90 degrees, your front hand at shoulder height.",
  "Every stroke begins with a perfect setup; pause, hold, and master the starting position.",
  "Feel the water with your paddle; a good catch starts with downward pressure through the shaft.",
  "In one-sided strokes, control the paddle angle using your backhand alone.",
  "Hips lead the motion, followed by the torso, shoulders, and finally the paddle.",
  "A quick recoil with the hip sets the rhythm for a balanced stroke.",
  "Maintain connection with the footrest—leg drive starts and ends with stable footing.",
  "Use the ‘robot drill’ to slow down and focus on power through every phase of the stroke.",
  "To finish strong, drive through your legs and let your posture lean back for maximum propulsion.",
  "Your paddle is most effective when it's vertical—keep it aligned with the boat’s path.",
  "Consistency in the catch and exit phases creates a seamless paddling rhythm.",
  "Pause drills teach control; hold your setup and feel the power in patience.",
  "A stable top hand at eye level ensures control and minimizes wasted energy.",
  "Every twist of the torso begins with the hips—start from the core.",
  "Balance the kayak with your body; unnecessary movements create drag.",
  "Develop muscle memory with repetition; perfection lies in practice.",
  "A proper catch requires both hands to press downward through the shaft.",
  "Exit with your knuckles leading the motion; keep water disturbance minimal.",
  "Let your blade guide you—tap into its natural angle for maximum grip.",
  "Paddle drills are the gym for technique; dedicate time to refinement daily.",
  "Engage your lower abdominals and keep your center of mass stable.",
  "In the ‘lunge drill,’ let your leg drive propel the kayak forward with every stroke.",
  "Use the ‘rock the boat’ drill to master the subtleties of start stroke control.",
  "In rotational drills, slow down and feel how your hips drive the entire motion.",
  "Correct errors one stroke at a time—there’s no rush to perfection.",
  "Focus on a two-handed catch; the connection will magnify your power.",
  "Practice holding the paddle at a 60-degree angle to optimize your setup.",
  "Keep your torso upright, never crunching forward or leaning to the side.",
  "In the ‘ear touch drill,’ let awareness of paddle positioning sharpen your catch.",
  "The ‘front hand touch drill’ trains precision; make every stroke deliberate.",
  "Minimize torso compression; your body is a pillar of power, not a pendulum.",
  "Controlled transitions from air time to water time make your rhythm unbreakable.",
  "Mastering the ‘see-saw drill’ hones your ability to maintain blade angle through the setup.",
  "The ‘five strokes with four twists’ drill reminds you that the hips are the engine of every stroke.",
  "In the start position, your blade should be buried and square to the boat for immediate propulsion.",
  "Let your drive phase end with a perfectly timed exit—power without waste.",
];