List<String> quotes = [
  "Master the stroke, and the speed will follow.",
  "The best paddlers don’t just race the water, they read it.",
  "Smoothness in your stroke is the key to power in your push.",
  "Consistency in technique is the foundation of speed.",
  "A perfect stroke is a conversation between body and boat.",
  "Technique is built one perfect stroke at a time.",
  "You can’t rush technique. Trust the process, and the results will come.",
  "The power of a strong paddler lies in the efficiency of their stroke.",
  "The fastest athlete isn’t always the strongest, but the one who perfects the technique.",
  "Speed comes from control, and control comes from perfect technique.",
  "A flawless stroke is the result of perfect timing, rhythm, and balance.",
  "Master the catch, and the release will follow.",
  "If your paddle doesn’t feel like an extension of your body, you’re not paddling yet.",
  "Each stroke is an opportunity to refine your skill and power.",
  "The more you focus on the details, the bigger the payoff in speed.",
  "In sprint canoeing, precision outpaces raw power every time.",
  "Focus on the finish—where the paddle meets the water makes all the difference.",
  "Effort is important, but technique makes the effort count.",
  "Your stroke is your signature. Make it powerful and precise.",
  "The art of paddling is in learning how to create the most power with the least effort.",
  "Warm up your body before the race, but don’t forget to warm up your mind.",
  "A proper warm-up sets the stage for a performance that surpasses the limit.",
  "Prepare your muscles, prime your mind, and get ready to race.",
  "The race doesn’t start at the starting line—it starts with the warm-up.",
  "A well-executed warm-up is a promise to your body that it’s time to perform.",
  "Prepare for the start like it’s the most important part of your race.",
  "Warm up thoroughly so that every stroke feels effortless from the start.",
  "The key to a strong race is a well-planned warm-up that gets you moving without fatigue.",
  "A proper warm-up means less energy wasted and more power delivered.",
  "Activate your core, engage your legs, and bring your arms to life before the race.",
  "Never skip the warm-up. It’s not just about getting ready—it’s about getting ahead.",
  "Flexibility and activation are your secret weapons in any sprint race.",
  "Take time to warm up. Your body will thank you when it’s time to compete.",
  "A great warm-up is a ritual—a set routine that gets you in the zone.",
  "The race is won before the start if your warm-up is spot-on.",
  "Start your warm-up with dynamic movements to bring your body to life.",
  "A good warm-up ensures you don’t just finish the race—you dominate it.",
  "Pre-race nerves are nothing a good warm-up can't manage.",
  "Think of your warm-up as a rehearsal for your race. Perfect it, and the performance will follow.",
  "Efficient warm-ups turn potential energy into kinetic power on the water.",
  "Activate your body in layers—work from the core to the extremities.",
  "Mental preparation is just as important as physical—so calm your mind during the warm-up.",
  "Your warm-up is the bridge between practice and peak performance.",
  "A great warm-up builds confidence by allowing you to feel strong and prepared.",
  "Warm up like the race depends on it—because it does.",
  "Don’t rush your warm-up—quality is better than quantity.",
  "With the right warm-up, you’re already racing before the gun goes off.",
  "The body that is properly warmed up is more than ready to race hard.",
  "The warm-up is the start of your race; treat it with the same focus and effort."
];